### ISSUE TITLE
Massive Todo List

### ISSUE THREAD

**Issue by y3ll0wlife** [TeamBulbbot/bulbbot-gw#1]
# Events
## resume
- [x] log to stdout
- [ ] log to channel

## shard_stage_update
- [ ] log to stdout
- [ ] log to channel

## guild_create
- [ ] create db entry
- [ ] log to channel 

## guild_update
- [ ] log to guild configured logging channel

## guild_delete
- [ ] delete db entry
- [ ] log to channel

## guild_unavailable
- [ ] log to stdout
- [ ] log to channel 

## guild_role_create
- [ ] log to guild configured logging channel

## guild_role_update
- [ ] log to guild configured logging channel

## guild_role_delete
- [ ] log to guild configured logging channel

## guild_member_addition
- [ ] log to guild configured logging channel

## guild_member_removal
- [ ] log to guild configured logging channel

## channel_create
- [ ] log to guild configured logging channel

## channel_update
- [ ] log to guild configured logging channel

## channel_delete
- [ ] log to guild configured logging channel

## category_create
- [ ] log to guild configured logging channel

## category_delete
- [ ] log to guild configured logging channel

## message
- [ ] automod (see that category for more info)

## message_update
- [ ] log to guild configured logging channel

## message_delete
- [ ] log to guild configured logging channel

## message_delete_bulk
- [ ] log to guild configured logging channel

## guild_ban_addition
- [ ] log to guild configured logging channel

## guild_ban_removal
- [ ] log to guild configured logging channel

## invite_create
- [ ] log to guild configured logging channel

## invite_delete
- [ ] log to guild configured logging channel

# Automod
- [ ] Website filtering
- [ ] Invite filter
- [ ] Blacklisted words
- [ ] Blacklisted tokens
- [ ] Mention spam

# Translation
- [ ] Add the translated strings

# Misc
- [ ] Remove all gateway code from https://github.com/TeamBulbbot/bulbbot/
